### PR TITLE
Laravel 11 support

### PR DESCRIPTION
**Pull request by dcodeaaron**
Existing v0.x releases to be retained in a renamed `master` branch to `0.x`. All `0.x.x` tags to come from this branch.

New project primary branch `1.x` will this branch merged into it providing the basis for the future and Laravel v11+ support. All `1.x.x` tags to come from this branch.

For more information see starter project Laravel 11 PR for details: https://github.com/DCODE-GROUP/project-starter/pull/50

### CODE REVIEW

**Comment by lionslair** [comment]
I think rename master to a 1.x branch
Create a 2.x branch for this version  When released this can be 2.0.0 version

that way if we need to make changes to older version we can.

**Review by lionslair — CHANGES_REQUESTED** [review]
see comment

**Review by andrewsirianni — APPROVED** [review]

**Comment by andrewsirianni** [comment]
Where did we get to with this one?  We good to merge?

**Comment by dcodeaaron** [comment]
> Where did we get to with this one? We good to merge?

@andrewsirianni  No, I've not had resources to come back and address comments which should be considered on all updated laravel 11 projects.

**Pull request merged**
